name: pack
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create zip directory
        run: |
          mkdir -p zipdir
      - name: Pack release
        run: |
          zip -r zipdir/data.zip assets pack.mcmeta pack.png
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.2
          release_name: Release
          draft: false
          files: |
            zipdir/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
